### ISSUE TITLE
Specifying an RDS configuration in the environment

### ISSUE THREAD

**Issue by hypoalex** [alienfast/elastic-beanstalk#16]
Can you provide an example of how to do this? It would be glorious.

**Comment by rosskevin** [comment]
Hello @richland, I just have a separate multi zone RDS instance up and connect to it with the normal `database.yml`.  

e.g.

```ruby
production:
  <<: *defaults
  database: acme_prod
  username: acme_prod
  password: a2pfXr4dQ1b3
  host: acme-db-1.xsonthuenokm3u.us-east-1.rds.amazonaws.com
```

I recall a possibility to deploy an RDS from your elastic beanstalk, but frankly that just scares me. While my elastic beanstalk instances can come and go, I feel safe with the idea that my RDS is always there, and managed entirely through the RDS interfaces (instead of through eb). 

If you do figure it out, please let me know and I'll gladly include it in the docs.

**Comment by richland** [comment]
I think this might actually become really appealing when Aurora is ready for primetime!

I've been trying along these lines and it's not working for me, the eb_deployer example uses a JSON configuration file -  https://github.com/ThoughtWorksStudios/eb_deployer/blob/master/samples/jruby_rails4/config/my_rds.json

I'm hoping to implement a simpler solution like:

    development:
      strategy: inplace_update
      options:
        aws:autoscaling:launchconfiguration:
        InstanceType: t1.micro
      aws:rds:dbinstance:
       DeletionPolicy: "Delete"
       properties:
         db_instance_class: db.m1.small
          allocated_storage: 5
          engine_version: 5.6
          engine: mysql

I'll try to dedicate some more time to this and get it working.

**Comment by richland** [comment]
I need to delve into this a bit more but I think the issue is that this is using V1 of the AWS API.

**Comment by rosskevin** [comment]
@richland are you referring to `eb_deployer` using V1? or are you referring to the convenience tasks using V1?  I only mention this for clarity, the convenience tasks in this gem don't really have anything to do with deployment.

**Comment by richland** [comment]
Yeah, I was referring to eb_deployer using V1, I'm not sure if the convenience tasks affect my use case at all. 

What I'm trying to do here is just spin up databases upon deployment. I'm skeptical that anyone else would really care about this (as you mentioned, it's kinda saner to just provision your DB separately) and it would be a lot of work to bring everything to V2. Just mentioning it here in case anyone else happens to run into this!

**Comment by rosskevin** [comment]
See #19

**Comment by hypoalex** [comment]
Fixed, thanks!
