### ISSUE TITLE
Unable to access environment variables in config.rb

### ISSUE THREAD

**Issue by djsegal** [alienfast/elastic-beanstalk#29]
I ran into this problem, when I wanted to add some variables to a server. Examples include:

+ GITHUB_TOKEN: <%= ENV["GITHUB_TOKEN"] %>
+ secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

**Comment by rosskevin** [comment]
ENV interpolation should already be available as it is built-in to dry-config.   Please check out the docs: 

https://github.com/alienfast/dry-config/blob/master/README.md#env-interpolationsubstitutionexpansion

We may want to make a better reference to it in our read me. If this isn't workable,  please let me know.  I'm not sure expanding this to support an erb tag only for env is the right choice.

**Comment by djsegal** [comment]
For future reference, I added the following code to my `application.rb` file:

```
    # allow interpolation of env variables for elastic beanstalk config
    EbConfig.instance_values["options"][:interpolation] = true
```

-------

+ I didn't make a `config/initializers` file because they aren't read on deployment
+ My syntax was changed 
  - from `GITHUB_TOKEN: <%= ENV["GITHUB_TOKEN"] %>`
  - to `GITHUB_TOKEN: #{GITHUB_TOKEN}`

**Comment by rosskevin** [comment]
I would expect to support interpolation without the need to turn it on.  Will you pr that as a default? Maybe add a quick test?

**Comment by djsegal** [comment]
@rosskevin sorry, i don't know what you mean by that. I scrapped my PR and just used dry-config's env interpolation.

The reason I had to add that line to `application.rb` is because `interpolation` is set to `false` in:
+ https://github.com/alienfast/elastic-beanstalk/blob/6f8e98ab3acec8b2f38f52f4f769949fe2071ebb/lib/elastic/beanstalk/config.rb#L25

**Comment by djsegal** [comment]
nvm. making pr now
