### ISSUE TITLE
Config RACK_ENV and/or RAILS_ENV in eb.yml

### ISSUE THREAD

**Issue by saturnflyer** [alienfast/elastic-beanstalk#41]
I'd like to configure RACK_ENV and RAILS_ENV in my config file.
For example, in an EB environment called 'staging' I run my rails app in production mode, not a staging mode.
The current config task explicitly overrides any of these values set as options here https://github.com/alienfast/elastic-beanstalk/blob/bf4f125dfc89aec6f1e8fe4083e999b404a82f37/lib/elastic/beanstalk/tasks/eb.rake#L164-L165

Is there some way to maintain these environment variables without overriding the `eb:config` task?
If not, would you be open to a patch to alter those lines to check if those variables are already set?

**Comment by rosskevin** [comment]
I'll look at the patch.  As long as it isn't confusing it should be acceptable.

**Comment by rosskevin** [comment]
Tests fail...I was wondering where that dig method came from.

```ruby
NoMethodError: undefined method `dig' for #<Hash:0x007f94948ba328>
lib/elastic/beanstalk/tasks/eb.rake:164:in `block (2 levels) in <top (required)>'
```

**Comment by saturnflyer** [comment]
I'm sorry about that. We used 2.3 locally. fix incoming...

**Comment by rosskevin** [comment]
Thanks! v1.1.13 pushed to rubygems
