### ISSUE TITLE
EBSmokeTester custom headers

### ISSUE THREAD

**Issue by killerham** [alienfast/elastic-beanstalk#48]
I'm trying to setup my elastic beanstalk instance as forced ssl and to do that I'm configuring my ngnix config as found here:
http://scottwb.com/blog/2013/10/28/always-on-https-with-nginx-behind-an-elb/

My problem is that the EbSmokeTester doesn't have any options to add the X-Forwarded-For header...

Or another option is to just add the X-Forwarded-For for the smoketester and it autmoatically handle the adding the IP.

**Comment by rosskevin** [comment]
The [SmokeTester](https://github.com/alienfast/elastic-beanstalk/blob/master/lib/elastic/beanstalk/smoke_tester.rb) is just a simple ruby utility.  You can use any code including your own in: 

```ruby
smoke_test: |
    lambda { |host|
      # your code here
    }
```

You can either write your own code, or you may submit a PR enhancing this code so it works for you.  I readily accept PRs.  If you aren't going to work on it, please go ahead and close this.

**Comment by killerham** [comment]
Sorry, I didn't realize that I could have just put https:// instead of http.
