### ISSUE TITLE
Solution Stack name changed

### ISSUE THREAD

**Issue by rgonsalves** [alienfast/elastic-beanstalk#58]
Upon running ```rake eb:package eb:deploy
```  you'll get ```64bit Amazon Linux 2015.03 v2.0.0 running Ruby 2.2 (Passenger Standalone)' is not a valid solution stack name```, followed by a long list of valid stacks. Choose one of those!

**Comment by rosskevin** [comment]
Not a bug with this gem, which is a rake wrapper around eb_deployer.
