### ISSUE TITLE
Issue with Beanstalk Deployment

### ISSUE THREAD

**Issue by puneeth-k** [alienfast/elastic-beanstalk#61]
Hi,

We are using the Elastic BeanStalk for the Production Servers Deployment.For the package we are using .zip extension.

When we are deploying with eb:deploy we are getting following error.

[2017-10-11 17:48:56 UTC][environment:ts-r5in-app4-b-0bb7ba5] Unable to unzip application source bundlerake aborted!
Elasticbeanstalk instance provision failed (maybe a problem with your .ebextension files). The original message: [Instance: i-01a2c28c949ad0645] Command failed on instance. Return code: 1 Output: (TRUNCATED)...eck that you have transferred or created the zipfile in the  appropriate BINARY mode and that you have compiled UnZip properly)
/opt/elasticbeanstalk/hooks/appdeploy/pre/01_unzip.rb:30:in `': Unable to unzip application source bundle (RuntimeError).
Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/01_unzip.rb failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.

When we dig in to the error we found that .zip extension will support for 65535 files and we have crossed more than that.

What will be the best possible way to deploy and do u support any other compressions such as .tar or .tar.gz  etc.

Thanks
Puneeth

**Comment by puneeth-k** [comment]
Hi,

We were using the Elastic Beanstalk verion 1.1.13

**Comment by JeremiahChurch** [comment]
Hi Puneeth - You're probably not running in to an issue with the zip format and maximum files or size. The Zip tool that is used on the default amazon instance (Info-ZIP 3.0 when I look) says that zip64 format (more than 65k files and 4GB) is automatically supported - http://www.info-zip.org/mans/zip.html

My first thought - are you running out of system memory during the unzip?

**Comment by rosskevin** [comment]
Closing - no response.
