### ISSUE TITLE
Unable to deploy to the Ruby 2.0 container

### ISSUE THREAD

**Issue by Yanchek99** [alienfast/elastic-beanstalk#9]
Unable to deploy to the new Ruby 2.0 container: 64bit Amazon Linux 2014.03 v1.0.1 running Ruby 2.0 (Puma)

Looks like the problamatic piece of code can be found here:
https://github.com/alienfast/elastic-beanstalk/blob/master/samples/real-world.yml#L56

rake aborted!
Elasticbeanstalk instance provision failed (maybe a problem with your .ebextension files). The original message: [Instance: i-1d053942 Module: AWSEBAutoScalingGroup ConfigSet: null] Command failed on instance. Return code: 1 Output: Error occurred during build: Command make_vendor_bundle_dir failed

**Comment by rosskevin** [comment]
I'm finally revisiting our deployment, updating the container to `64bit Amazon Linux 2015.03 v2.0.0 running Ruby 2.2 (Puma)`.

So far, most of the workarounds in the old eb.yml for .ebextensions are implemented.  I'll post an update once I have things worked out.

If anyone else wants to post samples of their files, I can try to distill the most relevant.  I'm also going to try and work in a sidekiq example.  Any shared gists are appreciated.

**Comment by rosskevin** [comment]
I updated the samples: https://github.com/alienfast/elastic-beanstalk/commit/f437133bc48092e98e2dc78d14f98caaedabf6cc

It seems that with recent EB containers, many of our workarounds are no longer needed and the configs are more straightforward out of the box.
